workers_dev = true
name = "my-react-router-worker"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }
services = [
  { binding = "API_WORKER", service = "kon-api" }
]
route = "*.kon.xyz/*"
vars = { ENVIRONMENT = "production"}

[placement]
mode = "smart"

[observability]
enabled = true

[env.staging]
route = "*.kululu.xyz/*"
vars = { ENVIRONMENT = "staging" }
