// Generated by Wrangler by running `wrangler types`

interface Env {
  ORBIS_CERAMIC_GATEWAY: string
  ORBIS_NODE_GATEWAY: string
  ORBIS_NODE_ENV: string
  CDP_CLIENT_API_KEY: string
  ALCHEMY_API_KEY: string
  API_WORKER: Fetcher
}
