// Generated by Wrangler by running `wrangler types`

// biome-ignore lint/correctness/noUnusedVariables: <explanation>
interface Env {
  ENVIRONMENT: string
  ORBIS_CERAMIC_GATEWAY: string
  ORBIS_NODE_GATEWAY: string
  ORBIS_NODE_ENV: string
  CDP_CLIENT_API_KEY: string
  ALCHEMY_API_KEY: string
  API_WORKER: Fetcher
}
