#:schema node_modules/wrangler/config-schema.json
name = "kon-pwa"
compatibility_date = "2024-11-12"
main = "./server.ts"
assets = { directory = "./build/client" }
services = [
  { binding = "API_WORKER", service = "kon-api" }
]
route = "*.kon.xyz/*"
vars = { ENVIRONMENT = "production"}

[placement]
mode = "smart"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[env.staging]
route = "*.kululu.xyz/*"
vars = { ENVIRONMENT = "staging" }
